# Generated by Django 4.2.3 on 2023-07-26 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menue', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pizzas',
        ),
    ]
